In [ ]:
####Backpropagation Algorithm...........................

In [7]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X,axis=0)
y = y/100

In [8]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [9]:
def derivatives_sigmoid(x):
    return x * (1 - x)

In [10]:
epoch=5 
lr=0.1
in1 = 2
hn = 3
on = 1 

In [11]:
wh=np.random.uniform(size=(in1,hn))
bh=np.random.uniform(size=(1,hn))
wout=np.random.uniform(size=(hn,on))
bout=np.random.uniform(size=(1,on))

In [16]:
for i in range(epoch):
    input1=sigmoid(np.dot(X,wh)+bh)
    output=sigmoid(np.dot(input1,wout)+bout) 
####This Commented one is not required for output but perform backward propagation so it's should be included ......but for o/p leave it.
hiddengrad = derivatives_sigmoid(input1)#     out_grad=(y-output)*derivatives_sigmoid(output)
#     wout+=input1.T.dot(out_grad)*lr
#     d_hidden_layer=output_grad.dot(wout.T)*hiddengrad
#     wh+=X.T.dot(d_hidden_layer)*lr
    print ("-----------Epoch-", i+1, "Starts----------")
    print("Input: \n" + str(X))
    print("Predicted Output: \n" ,output)
    print("Actual Output: \n" + str(y))

-----------Epoch- 1 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Predicted Output: 
 [[0.82418274]
 [0.81454111]
 [0.82758316]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
-----------Epoch- 2 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Predicted Output: 
 [[0.82506458]
 [0.81537886]
 [0.82847289]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
-----------Epoch- 3 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Predicted Output: 
 [[0.82592859]
 [0.8162    ]
 [0.82934447]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
-----------Epoch- 4 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Predicted Output: 
 [[0.82677529]
 [0.81700501]
 [0.83019845]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
-----------Epoch- 5 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1. 